name : Community Threads Wiki Updater

on:
    schedule:
        - cron: '0 0 * * *'  # This cron expression triggers the workflow every day at midnight UTC
    workflow_dispatch:

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Update Wiki
          env:
            REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
            REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
            REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
            REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
            GIST_ID: ${{ secrets.GIST_ID }}
            GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          run: |
            cd community-threads
            python main.py
